config/routes.rb
Rails.application.routes.draw do

  root "classes#index"

  resources :classes, only: [] do
    collection do
      get :meme
    end
  end

  resources :subscribers, only: [:new, :create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_api!, if: -> { request.headers["HTTP_AUTHORIZATION"].present? }
  skip_before_filter :verify_authenticity_token, if: -> { request.headers["HTTP_AUTHORIZATION"].present? }
  after_action :verify_authorized, unless: -> {devise_controller?}
  after_action :verify_policy_scoped, only: %i[index], unless: -> {devise_controller?}

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  responders :flash

  helper_method :namespace

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def user_not_authorized(exception)
    if request.headers["HTTP_AUTHORIZATION"].present?
      return render json: { error: t('unauthorized') }, status: :unauthorized
    else
      flash[:alert] = t('flash.not_authorized')
      redirect_to(request.referrer || root_path)
    end
  end

  def namespace
    names = self.class.to_s.split('::')
    return "null" if names.length < 2
    names[0..(names.length-2)].map(&:downcase).join('_')
  end

  def authenticate_api!
    authenticate_or_request_with_http_token do |token, options|
      api_key = ApiKey.not_expired.find_by_access_token(token)
      if api_key
        sign_in(:user, api_key.user)
      else
        return render json: { error: t('unauthorized') }, status: :unauthorized
      end
    end
  end

end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  
  after_action :verify_policy_scoped, only: %i[]
  after_action :verify_authorized, except: %i[index meme]
  respond_to :html

  def index
  end

  def meme
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  
  EMAIL_REGEX = /\A([-a-z0-9!\#$%&'*+\/=?^_`{|}~]+\.)*[-a-z0-9!\#$%&'*+\/=?^_`{|}~]+@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  after_action :verify_policy_scoped, only: %i[]
  after_action :verify_authorized, except: %i[new create]
  respond_to :html

  def new
  end

  def create
    if params['NAME'].present? && params['EMAIL'].present? && params['EMAIL'] =~ EMAIL_REGEX
      mailchimp = Gibbon::API.new
      begin
        mailchimp.lists.subscribe({id: params[:id], email: {email: params['EMAIL']}, merge_vars: {:NAME => params['NAME']}, double_optin: false})
      rescue => e
        flash[:alert] = e.message
        return render action: :new
      end    
    else
      flash[:alert] = "Você precisa informar seu nome e seu email para participar."
      return render action: :new
    end
  end

end

app/views/classes/index.html.slim
- content_for :title do
  = "Aulas de tango em Porto Alegre com Laura Rosa & Daniel Weinmann"
- content_for :description do
  = "Aprenda tango argentino de salão e descubra como sua vida pode se transformar através da dança"
- content_for :url do
  = root_url
#header_wrapper
  = image_tag 'photo.jpg', class: 'right'
  #header.row
    = link_to :root do
      h1 Tango <small>salón<br/>com</small> Ganas
    h2 Laura Rosa <small>&</small> Daniel Weinmann
#menu_wrapper
  #menu.row
    div data-magellan-expedition="fixed"
      dl class="sub-nav"
        dd data-magellan-arrival="classes"
          a href="#classes" Aulas
        dd data-magellan-arrival="photos"
          a href="#photos" Fotos
        dd data-magellan-arrival="videos"
          a href="#videos" Vídeos
        dd data-magellan-arrival="newsletter"
          a href="#newsletter" Novidades
        dd data-magellan-arrival="contact"
          a href="#contact" Contato
#classes_wrapper
  #classes.content.row data-magellan-destination="classes"
    h3= yield :description
    .row          
      .columns.small-12.medium-4
        ul class="pricing-table"
          li class="title" Terças-feiras
          li class="description" 2 vezes por semana, das 20h às 21h
          li class="bullet-item" Com Laura Rosa e Daniel Weinmann
          li class="bullet-item"
            p
              = "Studio de Dança Mara Noschang"
              .address Rua José do Patrocínio, 541
            a href="http://www.maranoschang.blogspot.com.br" target="_blank"
              i class="fi-web"
            a href="https://www.facebook.com/pages/Studio-de-Dan%C3%A7a-Mara-Noschang/210315652361363" target="_blank"
              i class="fi-social-facebook"
            a href="https://www.google.com.br/maps/place/Mara+Noschang/@-30.039881,-51.223454,17z/data=!3m1!4b1!4m2!3m1!1s0x95197901ce7d2461:0xa4a2a26deb90ee24?hl=pt-BR" target="_blank"
              i class="fi-marker"
          li class="bullet-item" Iniciantes e intermediários
          li class="bullet-item" R$ 120/mês individual (terças + quintas)
          li class="bullet-item" R$ 216/mês casal (terças + quintas)
          li class="cta-button"
            = mail_to 'contato@ganas.com.br', 'Quero me inscrever', class: 'button'
      .columns.small-12.medium-4
        ul class="pricing-table"
          li class="title" Quartas-feiras
          li class="description" 1 vez por semana, das 19h às 20h30
          li class="bullet-item" Com Daniel Weinmann
          li class="bullet-item"
            p
              = "MEME Santo de Casa Estação Cultural"
              .address Rua Lopo Gonçalves, 176
            a href="http://www.centromeme.com.br/" target="_blank"
              i class="fi-web"
            a href="https://www.facebook.com/memesantodecasa" target="_blank"
              i class="fi-social-facebook"
            a href="https://www.google.com.br/maps/place/MEME+Santo+de+Casa+Esta%C3%A7%C3%A3o+Cultural/@-30.040721,-51.219208,17z/data=!3m1!4b1!4m2!3m1!1s0x95197855afabd067:0x518ae6c878fb0682?hl=pt-BR" target="_blank"
              i class="fi-marker"
          li class="bullet-item" Iniciantes
          li class="bullet-item" R$ 90/mês individual
          li class="bullet-item" R$ 160/mês casal
          li class="cta-button"
            = mail_to 'contato@ganas.com.br', 'Quero me inscrever', class: 'button'
      .columns.small-12.medium-4
        ul class="pricing-table"
          li class="title" Quintas-feiras
          li class="description" 2 vezes por semana, das 20h às 21h
          li class="bullet-item" Com Laura Rosa e Daniel Weinmann
          li class="bullet-item"
            p
              = "Studio de Dança Mara Noschang"
              .address Rua José do Patrocínio, 541
            a href="http://www.maranoschang.blogspot.com.br" target="_blank"
              i class="fi-web"
            a href="https://www.facebook.com/pages/Studio-de-Dan%C3%A7a-Mara-Noschang/210315652361363" target="_blank"
              i class="fi-social-facebook"
            a href="https://www.google.com.br/maps/place/Mara+Noschang/@-30.039881,-51.223454,17z/data=!3m1!4b1!4m2!3m1!1s0x95197901ce7d2461:0xa4a2a26deb90ee24?hl=pt-BR" target="_blank"
              i class="fi-marker"
          li class="bullet-item" Iniciantes e intermediários
          li class="bullet-item" R$ 120/mês individual (terças + quintas)
          li class="bullet-item" R$ 216/mês casal (terças + quintas)
          li class="cta-button"
            = mail_to 'contato@ganas.com.br', 'Quero me inscrever', class: 'button'
#photos_wrapper
  #photos.content.row data-magellan-destination="photos"
    ul class="clearing-thumbs small-block-grid-3 medium-block-grid-5" data-clearing="true"
      - (1..9).each do |photo|
        li
          a href=image_path("photos/0#{photo}.jpg")
            = image_tag "photos/0#{photo}_th.jpg", class: 'th'
#videos_wrapper
  #videos.content.row data-magellan-destination="videos"
    .flex-video
      iframe width="614" height="345" src="http://www.youtube.com/embed/RzE5RFCQFfU?showinfo=0&controls=0" frameborder="0" allowfullscreen
    p Inscreva-se em nosso #{ link_to 'canal no YouTube', 'http://youtube.com/subscription_center?add_user=ganastango', target: :blank } e veja mais vídeos!
#newsletter_wrapper
  #newsletter.content.row data-magellan-destination="newsletter"
    div class="small-10 small-offset-1 medium-8 medium-offset-2 columns"
      h3 Receba nossas novidades em seu email<br/><small>E concorra todo mês a 1 mês de aulas grátis!</small>
      = form_tag "http://ganas.us10.list-manage.com/subscribe/post"
        = hidden_field_tag 'u', '1f48ce3370d35fb1232544e29'
        = hidden_field_tag 'id', '367de329f4'
        = text_field_tag 'NAME', nil, placeholder: 'Seu nome', label: 'name'
        = text_field_tag 'EMAIL', nil, placeholder: 'seu@email.com', label: 'email'
        = submit_tag "Quero receber novidades por email", class: 'small-12 columns'
#contact_wrapper
  #contact.content.row data-magellan-destination="contact"
    ul class="vcard small-10 small-offset-1 medium-8 medium-offset-2 large-6 large-offset-3 columns"
      li class="photo row"
        div class="small-8 small-offset-2 medium-6 medium-offset-3 columns"= image_tag 'profile.png'
      li class="fn" Laura Rosa e Daniel Weinmann
      li class="email"
        a href="mailto:contato@ganas.com.br" contato@ganas.com.br
      li class="tel" 51 9904-3244
      li class="url"
        a href="https://www.facebook.com/ganastango" target="_blank"
          i class="fi-social-facebook"
      li class="url"
        a href="https://youtube.com/ganastango" target="_blank"
          i class="fi-social-youtube"

app/views/classes/meme.html.slim
- content_for :title do
  = "Tango salón para iniciantes. Aulas regulares com Daniel Weinmann"
- content_for :description do
  = "Aprenda tango argentino de salão e descubra como sua vida pode se transformar através da dança"
#header_wrapper
  = image_tag 'photo.jpg', class: 'right'
  #header.row
    = link_to :root do
      h1 Tango <small>salón<br/>para</small> iniciantes
    h2 <small>Aulas regulares com</small> Daniel Weinmann
#service_wrapper
  #service.content.row
    .service <small>TODAS AS</small> QUARTAS<small>, das </small>19h<small> às </small>20h30
    .service MEME Santo de Casa <small>Estação Cultural</small>
    .service.small Lopo Gonçalves, 176 · R$ 90/mês individual · R$ 160/mês casal
#footer_wrapper
  #footer.content.row
    .service
      = mail_to "contato@ganas.com.br"
      = " · 51 9904-3244"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="robots" content="index, follow"
    meta name="viewport" content="initial-scale=1.0, width=device-width"
    - if content_for? :meta_tags
      / Page specific meta tags
      = yield :meta_tags
    - else
      / Meta tags for pages that don't have specific meta tags
      meta name="description" content==strip_tags(content_for?(:description) ? yield(:description) : yield(:title))
      meta name="keywords" content="#{yield :title} Ganas"
      meta property="og:title" content==yield(:title)
      meta property="og:type" content="website"
      meta property="og:url" content=(content_for?(:url) ? yield(:url) : request.url)
      meta property="og:image" content=="#{request.protocol}#{request.host_with_port}#{image_path("photo.jpg")}"
      meta property="og:description" content==strip_tags(content_for?(:description) ? yield(:description) : yield(:title))
      meta name="author" content="Laura Rosa & Daniel Weinmann"
    / Metatags for every page
    meta property="og:site_name" content="Ganas"
    meta property="fb:app_id" content=ENV['FACEBOOK_APP_ID']
    meta property="fb:admins" content=ENV['FACEBOOK_ADMINS']
    title== "#{"#{strip_tags(yield :title)} · " if content_for?(:title)} Ganas"
    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    - if content_for? :external_js
      = yield :external_js
    = javascript_include_tag "application"
    = csrf_meta_tag
  body[data-namespace="#{namespace}" data-controller="#{controller_name}" data-action="#{action_name}" data-locale="#{I18n.locale}"]
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43352814-1', 'auto');
      ga('send', 'pageview');
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '425920014241111',
          xfbml      : true,
          version    : 'v2.2'
        });
      };
      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    = yield

app/views/subscribers/_facebook_conversion.html.erb
<!-- Facebook Conversion Code for Cadastros novidades - Ganas -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6026153402770', {'value':'0.00','currency':'BRL'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6026153402770&amp;cd[value]=0.00&amp;cd[currency]=BRL&amp;noscript=1" /></noscript>

app/views/subscribers/create.html.slim
- content_for :title do
  = "Receba nossas novidades em seu email e concorra todo mês a 1 mês de aulas grátis!"
- content_for :description do
  = "Aprenda tango argentino de salão e descubra como sua vida pode se transformar através da dança"
- content_for :external_js do
  = render 'facebook_conversion'
#subscriber_wrapper
  #subscriber.content.row
    ul class="vcard small-10 small-offset-1 medium-8 medium-offset-2 large-6 large-offset-3 columns"
      li class="photo row"
        div class="small-8 small-offset-2 medium-6 medium-offset-3 columns"= image_tag 'profile.png'
    .row
      div class="small-10 small-offset-1 medium-8 medium-offset-2 columns"
        h3 Sua inscrição foi realizada com sucesso!<br/><small>Em breve você receberá novidades em seu email.</small>
        h4 Que tal agora conhecer #{ link_to 'nosso site', root_path }?

app/views/subscribers/new.html.slim
- content_for :title do
  = "Receba nossas novidades em seu email e concorra todo mês a 1 mês de aulas grátis!"
- content_for :description do
  = "Aprenda tango argentino de salão e descubra como sua vida pode se transformar através da dança"
#header_wrapper
  = image_tag 'photo.jpg', class: 'right'
  #header.row
    h1 Tango <small>salón<br/>com</small> Ganas
    h2 Laura Rosa <small>&</small> Daniel Weinmann
#subscriber_wrapper
  #subscriber.content.row
    div class="small-10 small-offset-1 medium-8 medium-offset-2 columns"
      h3 Receba nossas novidades em seu email<br/><small>E concorra todo mês a 1 mês de aulas grátis!</small>
      - if alert.present?
        div data-alert=true class="alert-box alert"
          = alert
          a href="#" class="close" &times;
      = form_tag subscribers_path
        = hidden_field_tag 'id', '367de329f4'
        = text_field_tag 'NAME', nil, placeholder: 'Seu nome', label: 'name'
        = text_field_tag 'EMAIL', nil, placeholder: 'seu@email.com', label: 'email'
        = submit_tag "Quero concorrer todo mês a 1 mês de aulas grátis", class: 'small-12 columns'